### ISSUE TITLE
buying multiple items

### ISSUE THREAD

**Issue by Ashember** [VORPCORE/VORP-Stores#1]
Buying multiple of the same item makes you get a "you do not have enough room error."   stat
<img width="405" alt="Screenshot_13" src="https://user-images.githubusercontent.com/23489428/89092317-9bb6a600-d37e-11ea-81b6-2239f9a97f5c.png">
<img width="514" alt="Screenshot_11" src="https://user-images.githubusercontent.com/23489428/89092320-a2ddb400-d37e-11ea-8d3f-30b75d6d9b12.png">
<img width="368" alt="Screenshot_12" src="https://user-images.githubusercontent.com/23489428/89092321-a5d8a480-d37e-11ea-8a81-6b1b7756997e.png">
<img width="237" alt="Screenshot_14" src="https://user-images.githubusercontent.com/23489428/89092330-c6086380-d37e-11ea-946e-3db292d8b589.png">

ing you are over weight. 

If you buy one item at a time you can buy up to max.

**Comment by DevBiiTz** [comment]
@Ashember go to config of your inventory and see you max inventory can carry items.

**Comment by Ashember** [comment]
it's at 1000  and it still does the same

**Comment by DevBiiTz** [comment]
screenshot

**Comment by Ashember** [comment]
You mean of this?

**Comment by Ashember** [comment]
<img width="221" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23489428/89093334-82662780-d387-11ea-8656-22cbb12700f8.png">

**Comment by DevBiiTz** [comment]
try with 1 item

**Comment by Ashember** [comment]
I did.. used to work but stopped with last update.
