### ISSUE TITLE
I can't buy any kind of product from the general store

### ISSUE THREAD

**Issue by williamw7** [VORPCORE/VORP-Stores#4]
I don't get any errors in console, but when I click on the product, neither money goes nor comes to the inventory

**Comment by rubi216** [comment]
Have you checked the game console?

**Comment by williamw7** [comment]
yea I've tried all versions of vorp store many times. Could there be a problem with database?

**Comment by williamw7** [comment]
my previous server is ok, but when i enter another server i get this error with the package

**Comment by rubi216** [comment]
Try with this pre built server: [https://drive.google.com/file/d/1mv43QC8fbAB9wv-pGnWlGyXiMqbtP3cI/view?usp=sharing](https://drive.google.com/file/d/1mv43QC8fbAB9wv-pGnWlGyXiMqbtP3cI/view?usp=sharing)

**Comment by williamw7** [comment]
thanks rubi fixed I switched the server I used from server 2019 to windows 10.

**Comment by rubi216** [comment]
Perfect!
